version: '3.8'

services:
  playwright-test:
    build: .
    container_name: playwright-container
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
