name: CI/CD Pipeline with Docker and Playwright

on:
  push:
    branches:
      - main  # Ejecutar en push hacia la rama main
  pull_request:
    branches:
      - main  # Ejecutar en pull request hacia la rama main

jobs:
  build:
    runs-on: ubuntu-latest  # Usar una máquina con Ubuntu para ejecutar el pipeline

    steps:
      # Paso 1: Hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker y Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Instalar Docker Compose

      # Paso 3: Ejecutar pruebas en contenedor Docker
      - name: Run tests with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from playwright-test

      # Paso 4: Extraer los informes de Allure después de que el contenedor termine
      - name: Copy Allure reports from volume
        run: |
          docker cp playwright-container:/app/allure-report ./allure-history/allure-report
          docker cp playwright-container:/app/allure-results ./allure-history/allure-results



      # Paso 5: Limpiar los contenedores Docker
      - name: Clean up Docker containers
        run: |
          docker-compose -f docker-compose.yml down --volumes --remove-orphans

  # Nuevo job para visualizar el reporte de Allure
  show_allure_report:
    runs-on: ubuntu-latest  # Usar Ubuntu
    needs: build  # Este job necesita que el job `build` haya terminado correctamente

    steps:
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: ./allure-history/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history