name: CI/CD Pipeline with Docker and Playwright

on:
  push:
    branches:
      - main  # Ejecutar en push hacia la rama main
  pull_request:
    branches:
      - main  # Ejecutar en pull request hacia la rama main

jobs:
  build:
    runs-on: ubuntu-latest  # Usar una máquina con Ubuntu para ejecutar el pipeline

    steps:
      # Paso 1: Hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker y Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Instalar Docker Compose

      # Paso 3: Ejecutar pruebas en contenedor Docker
      - name: Run tests with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build --abort-on-container-exit --exit-code-from playwright-test

      # Paso 4: Extraer los informes de Allure después de que el contenedor termine
      - name: Extract Allure reports from container
        run: |
          docker cp playwright-container:/app/allure-report ./allure-report
          docker cp playwright-container:/app/allure-results ./allure-results

      # Paso 5: Limpiar los contenedores Docker
      - name: Clean up Docker containers
        run: |
          docker-compose -f docker-compose.yml down --volumes --remove-orphans

      # Paso 6: Publicar el informe de Allure
      - name: Publish Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

  # Este trabajo es para mostrar el reporte de Allure en GitHub Actions (opcional)
  allure-report:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report

      - name: Show Allure report (optional)
        run: |
          echo "Allure report is ready."